taskapp/config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks, only: [:show, :create, :destroy]
  end

  resources :users do
    resources :works, only: [:show, :create]
  end



  post '/users/:user_id/works/count' => 'works#count'


  root 'users#index'









end

taskapp/app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  validates :title,
  presence: { message: "入力してください" }, 
  length: { minimum: 3, message: "短すぎ!" } 
end

taskapp/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  validates :title, presence: true
end

taskapp/app/models/user.rb
class User < ActiveRecord::Base
  has_many :works
  validates :username,
  presence: { message: "入力してください" },
  length: { minimum: 3, message: "短すぎ!" }
end

taskapp/app/models/work.rb
class Work < ActiveRecord::Base
  belongs_to :user
  scope :finished, -> { where(done: true) }
  scope :unfinished, -> { where(done: false) }
end

taskapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

taskapp/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to projects_path
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

    def project_params
      params[:project].permit(:title)
    end

    def set_project
      @project = Project.find(params[:id])
    end

end

taskapp/app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_project, only: [:show, :destroy, :toggle]

  def show
    #@user = User.find(params[:user_id])
    @user = User.find(1)
  end

  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.create(task_params)
    redirect_to project_path(@project.id)
  end

  def destroy
    @task.destroy
    redirect_to project_path(params[:project_id])
  end

  def toggle
    #render nothing: true
    #@project = Project.find(params[:project_id])
    #@task.done = !@task.done
    #@task.save
    @user = User.find(params[:user_id])
    @task = Task.find(params[:id])
    @work = @user.works.create
    if request.xhr?
=begin
      if @task.done
        render partial: 'projects/complete_btn', locals: { id: @task.id, project_id: @task.project_id }
      else
        render partial: 'projects/incomplete_btn', locals: { id: @task.id, project_id: @task.project_id }
      end
=end
      #render partial: 'projects/count'
      render text: "test"
    end
  end

  private

    def task_params
      params[:task].permit(:title)
    end

    def set_project
      #@task = Task.find(params[:id])
      @task = Task.eager_load(:project).find(params[:id])
    end

end

taskapp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    #@tasks = Task.all
    @tasks = Task.eager_load(:project)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

    def user_params
      params[:user].permit(:username)
    end

    def set_user
      @user = User.find(params[:id])
    end

end

taskapp/app/controllers/works_controller.rb
class WorksController < ApplicationController

  before_action :set_user, only: [:show, :destroy, :toggle]

  def show
  end

  def create
    render nothing: true
    if (params.has_key?(:user_id) && params.has_key?(:task_id))
      @work = Work.where('user_id = ? AND task_id = ?',
        params[:user_id], params[:task_id]).first
        #Rails.logger.debug("My object: #{@work.inspect}")
      if @work.present?
        @work.done = !@work.done
        @work.save
      else
        @user = User.find(params[:user_id])
        @work = @user.works.create(work_params)
        @work.task_id = params[:task_id]
        @work.done = !@work.done
        @work.save
      end
    end
  end

  def destroy
    @work.destroy
    redirect_to user_path(params[:user_id])
  end

  def count
    @user = User.find(params[:user_id])
    if request.xhr?
      render partial: 'users/count'
    end
  end

  def toggle
    #render nothing: true
    @user = User.find(params[:user_id])
    @task = Task.find(params[:id])
    @work = @user.works.create
    #@user.done = !@user.done
    #@user.save
    #@work = Work.where('user_id = ? AND task_id = ?', @user.id, @task.id)
    render text: "test"
  end

  private

    def work_params
      params[:work]
    end

    def set_user
      @work = Work.find(params[:id])
    end

end

taskapp/app/helpers/application_helper.rb
module ApplicationHelper
end

taskapp/app/helpers/projects_helper.rb
module ProjectsHelper
end

taskapp/app/helpers/tasks_helper.rb
module TasksHelper
end

taskapp/app/helpers/users_helper.rb
module UsersHelper
end

taskapp/app/helpers/works_helper.rb
module WorksHelper
end

taskapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taskapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= image_tag "logo.png" %>

<%= yield %>

<%= link_to "Home", "/" %>

</body>
</html>

taskapp/app/views/projects/_count.html.erb
count: <%= @project.tasks.count %>

taskapp/app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
  <% if @project.errors.any? %>
    <%= @project.errors.messages[:title][0] %>
  <% end %>
</p>

<p>
<%= f.submit %>
</p>

<% end %>

taskapp/app/views/projects/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

taskapp/app/views/projects/index.html.erb
<h1>Projects</h1>

<ul>
  <% @projects.each do |project| %>
  <li>
  <%= link_to project.title, project_path(project.id) %> (<%= project.tasks.count %>)
  <%= link_to "[Edit]", edit_project_path(project.id) %>
  <%= link_to "[Delete]", project_path(project.id), method: :delete, data: { confirm: "are you sure?" } %>
  </li>
  <% end %>
</ul>

<p><%= link_to "Add New", new_project_path %></p>

taskapp/app/views/projects/new.html.erb
<h1>New</h1>

<%= render 'form' %>

taskapp/app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<div id="count">
<%= render partial: 'projects/count' %>
</div>

<ul>
<% @project.tasks.each do |task| %>
<li>
  <%= link_to task.title, project_task_path(task.project_id, task.id), method: :get %>
  <%= task.id %>
  <%= link_to "[Delete]", project_task_path(task.project_id, task.id), method: :delete, data: { confirm: "are you sure?" } %>
</li>
<% end %>
<li>
  <%= form_for [@project, @project.tasks.build] do |f| %>
  <%= f.text_field :title %>
  <%= f.submit %>
  <% end %>
</li>
</ul>

taskapp/app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<%= @task.id %>
<%= @task.project.title %>
<%= link_to "[Delete]", project_task_path(@task.project_id, @task.id), method: :delete, data: { confirm: "are you sure?" } %>

<% if Work.where('user_id = ? AND task_id = ? AND done = ?',@user.id, @task.id, true).first then %>
<div id="task-<%= @task.id %>">
<%= render partial: 'users/complete_btn',
  locals: {user_id: @user.id, task_id: @task.id} %>
</div>
<% else %>
<div id="task-<%= @task.id %>">
<%= render partial: 'users/incomplete_btn',
  locals: {user_id: @user.id, task_id: @task.id} %>
</div>
<% end %>

taskapp/app/views/users/_complete_btn.html.erb
<span class="btn btn-success" data-user_id="<%= user_id %>" data-task_id="<%= task_id %>" data-remote="true"><i class="glyphicon glyphicon-ok-circle">完了</i></span>

taskapp/app/views/users/_count.html.erb
finished count: <%= @user.works.finished.count %>

taskapp/app/views/users/_form.html.erb
<%= form_for @user do |f| %>

<p>
  <%= f.label :username %><br>
  <%= f.text_field :username %>
  <% if @user.errors.any? %>
    <%= @user.errors.messages[:username][0] %>
  <% end %>
</p>

<p>
<%= f.submit %>
</p>

<% end %>

taskapp/app/views/users/_incomplete_btn.html.erb
<span class="btn btn-default" data-user_id="<%= user_id %>" data-task_id="<%= task_id %>" data-remote="true"><i class="glyphicon glyphicon-ban-circle">未完了</i></span>

taskapp/app/views/users/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

taskapp/app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
  <li>
  <%= link_to user.username, user_path(user.id) %>
  <%= link_to "[Edit]", edit_user_path(user.id) %>
  <%= link_to "[Delete]", user_path(user.id), method: :delete, data: { confirm: "are you sure?" } %>
  </li>
  <% end %>
</ul>

<p><%= link_to "Add New", new_user_path %></p>

taskapp/app/views/users/new.html.erb
<h1>New</h1>

<%= render 'form' %>

taskapp/app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<div id="count">
<%= render partial: 'users/count' %>
</div>

<ul>
<% @tasks.each do |task| %>
<li>
  <%= link_to task.title, project_task_path(task.project_id, task.id), method: :get %>
  <%= task.id %>
  <%= task.project_id %>
  <%= task.project.title %>
  <% if Work.where('user_id = ? AND task_id = ? AND done = ?',@user.id, task.id, true).first then %>
  <div id="task-<%= task.id %>">
  <%= render partial: 'users/complete_btn',
    locals: {user_id: @user.id, task_id: task.id} %>
  </div>
  <% else %>
  <div id="task-<%= task.id %>">
  <%= render partial: 'users/incomplete_btn',
    locals: {user_id: @user.id, task_id: task.id} %>
  </div>
  <% end %>
</li>
<% end %>
</ul>